version: "3.8"

services:
  versitygw:
    image: versity/versitygw:v1.8.0
    restart: unless-stopped
    environment:
      - ROOT_ACCESS_KEY=${ROOT_ACCESS_KEY}
      - ROOT_SECRET_KEY=${ROOT_SECRET_KEY}
      - VGW_BACKEND=posix
      - VGW_PORT=:7070
      - VGW_BACKEND_ARGS=/data/s3
      - VGW_IAM_DIR=/data/iam
      - VGW_VERSIONING_DIR=/data/versioning
      - VGW_ADMIN_PORT=:7071
      - VGW_WEBUI_PORT=:8080
      - VGW_WEBUI_NO_TLS=true
      - VGW_WEBUI_GATEWAYS=http://localhost:7070
      - VGW_WEBUI_ADMIN_GATEWAYS=http://localhost:7071
    expose:
      - "7070"
      - "7071"
      - "8080"
    volumes:
      - versitygw_s3:/data/s3
      - versitygw_versioning:/data/versioning
      - versitygw_iam:/data/iam
volumes:
  versitygw_s3:
  versitygw_versioning:
  versitygw_iam:
