[variables]
main_domain = "${domain}"
ROOT_ACCESS_KEY = "${access_key:16}"
ROOT_SECRET_KEY = "${password:32}"

[config]
env = {}
mounts = []

[[config.domains]]
serviceName = "versitygw"
port = 8080
host = "${main_domain}"
